aloha-agilex:
  file_path: "${ASSETS_PATH}/assets/embodiments/aloha-agilex/"

piper:
  file_path: "${ASSETS_PATH}/assets/embodiments/piper"

franka-panda:
  file_path: "${ASSETS_PATH}/assets/embodiments/franka-panda/"

ARX-X5:
  file_path: "${ASSETS_PATH}/assets/embodiments/ARX-X5"

ur5-wsg:
  file_path: "${ASSETS_PATH}/assets/embodiments/ur5-wsg"
